export const RULESET_VERSION = "rover-rem-guide-2026-05-23-v1";

export const SOURCE_LINKS = [
  {
    label: "Rules tuned from Rover & Rem's community lootrun guide, last updated 23/05/2026.",
    href: null,
  },
];

export const SEARCH_MODES = {
  rollout: {
    label: "Monte Carlo rollout",
    optionHint: "fast, lighter",
    description: "Fast stochastic rollouts using the current policy. Best when you need a quick answer while playing.",
  },
  mcts: {
    label: "MCTS",
    optionHint: "smarter, slower",
    description: "Tree search with visits, UCB exploration, and average utility. Best for setup chains and high-impact choices.",
  },
};

export const COMPUTE_MODES = {
  light: {
    label: "Light",
    rollouts: 48,
    horizon: 5,
    mctsIterations: 120,
    mctsDepth: 5,
    description: "Lowest CPU cost for fast in-run decisions.",
  },
  balanced: {
    label: "Balanced",
    rollouts: 144,
    horizon: 8,
    mctsIterations: 420,
    mctsDepth: 8,
    description: "Recommended live-play setting.",
  },
  deep: {
    label: "Deep",
    rollouts: 360,
    horizon: 12,
    mctsIterations: 1200,
    mctsDepth: 12,
    description: "Stronger search when you can wait a moment.",
  },
  max: {
    label: "Max",
    rollouts: 720,
    horizon: 16,
    mctsIterations: 2600,
    mctsDepth: 16,
    description: "Heaviest mode, intended for desktop or patient planning.",
  },
};

export const PLAYER_PROFILES = {
  safe: {
    label: "Safe",
    optionHint: "safer, timer first",
    clearSpeed: 0.82,
    riskTolerance: 0.72,
    timeValue: 1.22,
    curseTolerance: 0.72,
  },
  balanced: {
    label: "Balanced",
    optionHint: "recommended",
    clearSpeed: 1,
    riskTolerance: 1,
    timeValue: 1,
    curseTolerance: 1,
  },
  greed: {
    label: "Greed",
    optionHint: "more pulls, riskier",
    clearSpeed: 1.12,
    riskTolerance: 1.28,
    timeValue: 0.86,
    curseTolerance: 1.22,
  },
  speed: {
    label: "Fast Clear",
    optionHint: "for fast builds",
    clearSpeed: 1.24,
    riskTolerance: 1.08,
    timeValue: 0.92,
    curseTolerance: 1,
  },
};

export const DEFAULT_WEIGHTS = {
  pull: 100,
  rewardReroll: 145,
  sacrifice: 270,
  beaconReroll: 92,
  boon: 58,
  boonPotency: 0.42,
  flyingChest: 34,
  missionSlot: 310,
  trialSlot: 360,
  challenge: 88,
  futureChoice: 66,
  second: 0.38,
  curse: -44,
  radianceCurse: -31,
  danger: -240,
  blockedCombo: -95,
  redDebtSecond: -0.46,
  redDebtChallenge: -34,
};

export const BEACON_IDS = [
  "blue",
  "purple",
  "yellow",
  "aqua",
  "orange",
  "green",
  "darkGrey",
  "white",
  "grey",
  "red",
  "pink",
  "crimson",
  "rainbow",
];

export const BEACONS = {
  blue: {
    id: "blue",
    name: "Blue Beacon",
    shortName: "Blue",
    tone: "#3b82f6",
    unlock: "Rookie I",
    baseWeight: 1,
    rarity: "Common",
    effect: "Choose 1 Boon from 4 choices at 100% potency.",
    reason: "Boon sustain is central after Fruma and builds the bank used to cash out Purple/Opal lines later.",
    extraNotes: "Base / Vibrant / Vibrant + Aqua potency is 100% / 200% / 600%.",
  },
  purple: {
    id: "purple",
    name: "Purple Beacon",
    shortName: "Purple",
    tone: "#8b5cf6",
    unlock: "Rookie I",
    baseWeight: 1,
    rarity: "Common",
    effect: "+1 Curse, +1 End Reward Pull.",
    reason: "Immediate pull value, but early curses make the whole run harder without support missions.",
    extraNotes: "Base / Vibrant / Vibrant + Aqua is 1 / 2 / 6 curses and pulls.",
  },
  yellow: {
    id: "yellow",
    name: "Yellow Beacon",
    shortName: "Yellow",
    tone: "#facc15",
    unlock: "Rookie I",
    baseWeight: 1,
    rarity: "Common",
    effect: "Spawn 1 Flying Chest.",
    reason: "Strong with Materialism, Hoarder, or a fast chest route.",
    extraNotes: "Base / Vibrant / Vibrant + Aqua is 1 / 2 / 6 flying chests.",
  },
  aqua: {
    id: "aqua",
    name: "Aqua Beacon",
    shortName: "Aqua",
    tone: "#22d3ee",
    unlock: "Rookie II",
    baseWeight: 1,
    rarity: "Common",
    noConsecutive: true,
    effect: "+100% to the next beacon.",
    reason: "Essential for almost any premium beacon; Vibrant Aqua enables x6 stacked payoffs.",
    extraNotes: "Aqua can never appear twice in a row; /kill or dying before the next challenge removes it.",
  },
  orange: {
    id: "orange",
    name: "Orange Beacon",
    shortName: "Orange",
    tone: "#fb923c",
    unlock: "Rookie III",
    baseWeight: 0.74,
    rarity: "Medium early / rare at 3 choices",
    effect: "+1 beacon choice for 5 challenges.",
    reason: "Improves future choice quality and helps find premium beacons sooner.",
    extraNotes: "Base / Vibrant / Vibrant + Aqua is +1 choice for 5 / 10 / 30 challenges. Cap is 6 choices.",
  },
  green: {
    id: "green",
    name: "Green Beacon",
    shortName: "Green",
    tone: "#22c55e",
    unlock: "Assistant II",
    baseWeight: 1,
    rarity: "Common",
    noConsecutive: true,
    effect: "+120s Time Bonus; mobs gain no buffs this challenge only.",
    reason: "Repairs low timer states; strongest after Red-heavy paths become urgent, not when the clock is already safe.",
    extraNotes: "Time is 120 / 240 / 720s. The no-buff duration is 1 / 2 / 3 challenges and is affected by Aqua, not standalone Vibrant.",
  },
  darkGrey: {
    id: "darkGrey",
    name: "Dark Grey Beacon",
    shortName: "Dark Grey",
    tone: "#64748b",
    unlock: "Sentinel I",
    baseWeight: 0.2,
    rarity: "Rare",
    maxUses: 1,
    effect: "+3 Curses, +3 End Reward Pulls.",
    reason: "Huge pull spike when Inner Peace, Cleansing, or Equilibrium can absorb curse.",
    extraNotes: "Dark Grey becomes rarer after challenge 10.",
  },
  white: {
    id: "white",
    name: "White Beacon",
    shortName: "White",
    tone: "#f8fafc",
    unlock: "Sentinel III",
    baseWeight: 0.2,
    rarity: "Rare",
    maxUses: 1,
    effect: "+5 Challenges.",
    reason: "Raises the run ceiling when timer and boon economy can support it.",
    extraNotes: "White becomes rarer after challenge 10.",
  },
  grey: {
    id: "grey",
    name: "Grey Beacon",
    shortName: "Grey",
    tone: "#94a3b8",
    unlock: "Elite I",
    baseWeight: 1,
    rarity: "Common after first mission",
    maxUses: 3,
    effect: "Choose a Mission out of 3.",
    reason: "Missions define the run; take Grey after setup is stable and no mission is pending.",
    extraNotes: "Base / Vibrant / Vibrant + Aqua is 3 / 4 / 5 mission choices. Grey appears only after the first mission is completed and fades around challenge 40-45 or after repeated skips.",
  },
  red: {
    id: "red",
    name: "Red Beacon",
    shortName: "Red",
    tone: "#ef4444",
    unlock: "Elite III",
    baseWeight: 1,
    rarity: "Common",
    noConsecutive: true,
    effect: "+3 Challenges with no matching time bonus.",
    reason: "Adds pull ceiling but creates explicit no-time-bonus debt.",
    extraNotes: "Base / Vibrant / Vibrant + Aqua is +3 / +5 / +15 no-time challenges. Red is removed if the challenge cap would be reached.",
  },
  pink: {
    id: "pink",
    name: "Pink Beacon",
    shortName: "Pink",
    tone: "#fb7185",
    unlock: "Admiral",
    baseWeight: 0.74,
    rarity: "Medium early / rare at 3 choices",
    effect: "+1 Beacon Reroll.",
    reason: "Adds reroll supply, lowering future reroll opportunity cost.",
    extraNotes: "Base / Vibrant / Vibrant + Aqua is +1 / +2 / +6 beacon rerolls.",
  },
  crimson: {
    id: "crimson",
    name: "Crimson Beacon",
    shortName: "Crimson",
    tone: "#b91c1c",
    unlock: "Admiral",
    baseWeight: 0.48,
    rarity: "Medium / rare at 3 choices",
    maxUses: 2,
    effect: "Choose a Trial out of 2.",
    reason: "Trials create reroll, sacrifice, or pull spikes; boosted Crimson is close to mandatory.",
    extraNotes: "Cannot show before challenge 20. Base / Vibrant / Vibrant + Aqua is 2 / 3 / 4 trial choices. Fades around challenge 65-70 or after repeated skips.",
  },
  rainbow: {
    id: "rainbow",
    name: "Rainbow Beacon",
    shortName: "Rainbow",
    tone: "#a855f7",
    unlock: "Master",
    baseWeight: 0.2,
    rarity: "Rare",
    effect: "Next beacons become vibrant for 10 challenges.",
    reason: "Run setup priority; makes Orange, Blue, White, Red, Grey, Crimson, and Green lines explode in value.",
    extraNotes: "Base / Vibrant / Vibrant + Aqua is 10 / 20 / 60 vibrant challenges.",
  },
};

export const MISSION_IDS = [
  "cleansingGreed",
  "materialism",
  "hoarder",
  "jestersTrick",
  "interestScheme",
  "orphionsGrace",
  "opalOffering",
  "stasis",
  "gourmand",
  "porphyrophobia",
  "sacrificialRitual",
  "radiantHunter",
  "equilibrium",
  "innerPeace",
  "optimism",
  "backupBeat",
  "requiem",
  "chronokinesis",
  "thrillSeeker",
  "highRoller",
  "redemption",
  "completeChaos",
];

export const MISSIONS = {
  cleansingGreed: {
    id: "cleansingGreed",
    name: "Cleansing Greed",
    archetype: "chest",
    reward: "After opening a Flying Chest, remove one Curse.",
    synergy: ["yellow", "materialism", "interestScheme"],
    baseScore: 82,
  },
  materialism: {
    id: "materialism",
    name: "Materialism",
    archetype: "chest",
    reward: "Spawns 2 flying chests after every challenge completed.",
    synergy: ["yellow", "hoarder", "jestersTrick"],
    baseScore: 92,
  },
  hoarder: {
    id: "hoarder",
    name: "Hoarder",
    archetype: "chest",
    reward: "After opening 7 Chests, choose 1 Boon out of 3.",
    synergy: ["yellow", "materialism", "interestScheme"],
    baseScore: 74,
  },
  jestersTrick: {
    id: "jestersTrick",
    name: "Jester's Trick",
    archetype: "chest",
    reward: "After 30 Flying Chest item offers, randomly gain +3 Pulls, +1 Boon, +1 Curse, or +30s.",
    synergy: ["yellow", "materialism", "hoarder"],
    baseScore: 70,
  },
  interestScheme: {
    id: "interestScheme",
    name: "Interest Scheme",
    archetype: "chest",
    reward: "Gaining 2 Pulls adds one Flying Chest to your next Yellow Beacon. Max 12.",
    synergy: ["yellow", "hoarder", "materialism"],
    baseScore: 72,
  },
  orphionsGrace: {
    id: "orphionsGrace",
    name: "Orphion's Grace",
    archetype: "boon",
    reward: "Boons are now 50% more effective.",
    synergy: ["blue", "porphyrophobia", "rainbow"],
    baseScore: 78,
  },
  opalOffering: {
    id: "opalOffering",
    name: "Opal Offering",
    archetype: "curse-stack",
    reward: "After getting a Curse, consume 1 Boon to gain +2 Pulls, plus +1 per 50% Potency.",
    synergy: ["purple", "darkGrey", "blue", "radiantHunter", "sacrificialRitual"],
    baseScore: 96,
  },
  gourmand: {
    id: "gourmand",
    name: "Gourmand",
    archetype: "reroll",
    reward: "Gain +1 Beacon Choice when you use a Beacon Reroll. Max 6; resets when a challenge begins.",
    synergy: ["optimism", "blue", "pink"],
    baseScore: 84,
  },
  porphyrophobia: {
    id: "porphyrophobia",
    name: "Porphyrophobia",
    archetype: "curse-stack",
    reward: "Getting offered Purple gives +1 Curse. Purple Beacons now give twice as many Pulls.",
    synergy: ["purple", "innerPeace", "opalOffering"],
    baseScore: 88,
  },
  sacrificialRitual: {
    id: "sacrificialRitual",
    name: "Sacrificial Ritual",
    archetype: "sacrifice",
    reward: "After finishing a Challenge, consume 1 Pull to gain +3 Challenges.",
    synergy: ["purple", "highRoller", "redemption"],
    baseScore: 76,
  },
  radiantHunter: {
    id: "radiantHunter",
    name: "Radiant Hunter",
    archetype: "greed",
    reward: "Defeating a Radiant Challenge mob grants +1 Pulls, 5 max per challenge.",
    synergy: ["opalOffering", "jestersTrick", "chronotrigger", "lightsOut"],
    baseScore: 86,
  },
  equilibrium: {
    id: "equilibrium",
    name: "Equilibrium",
    archetype: "curse-stack",
    reward: "Gaining a Curse boosts the Potency of your next boon by +50%. Max +300%.",
    synergy: ["purple", "darkGrey", "blue", "orphionsGrace"],
    baseScore: 94,
  },
  innerPeace: {
    id: "innerPeace",
    name: "Inner Peace",
    archetype: "stabilize",
    reward: "Curses are now half as effective.",
    synergy: ["purple", "darkGrey", "highRoller", "allIn"],
    baseScore: 82,
  },
  optimism: {
    id: "optimism",
    name: "Optimism",
    archetype: "reroll",
    reward: "When a beacon is rerolled, it will not be re-offered unless you run out of options.",
    synergy: ["gourmand", "pink", "blue"],
    baseScore: 80,
  },
  backupBeat: {
    id: "backupBeat",
    name: "Backup Beat",
    archetype: "timer",
    reward: "Every time you add +300s to your timer, gain +1 Beacon Reroll.",
    synergy: ["green", "aqua", "stasis"],
    baseScore: 82,
  },
  requiem: {
    id: "requiem",
    name: "Requiem",
    archetype: "stabilize",
    reward: "For the next 15 minutes, Enemy stat increases are voided.",
    synergy: ["radiantHunter", "red", "crimson"],
    baseScore: 74,
  },
  stasis: {
    id: "stasis",
    name: "Stasis",
    archetype: "timer",
    reward: "While picking a Beacon, your timer does not decrease. Max 5m.",
    synergy: ["deepPlanning", "rainbow", "crimson"],
    baseScore: 75,
  },
  chronokinesis: {
    id: "chronokinesis",
    name: "Chronokinesis",
    archetype: "timer",
    reward: "(Non-flying) chests now give +1 Pull, but consume timer. Completing a challenge reduces this penalty.",
    synergy: ["stasis", "green", "backupBeat"],
    baseScore: 72,
  },
  thrillSeeker: {
    id: "thrillSeeker",
    name: "Thrill Seeker",
    archetype: "greed",
    reward: "Red Beacons will reward 1 Boon out of 5.",
    synergy: ["red", "purple", "rainbow"],
    baseScore: 78,
  },
  highRoller: {
    id: "highRoller",
    name: "High Roller",
    archetype: "pull",
    reward: "Gain +10 Pulls and +1 End Reward Reroll.",
    immediate: { pulls: 10, rewardRerolls: 1 },
    synergy: ["redemption", "treasuryBill"],
    baseScore: 92,
  },
  redemption: {
    id: "redemption",
    name: "Redemption",
    archetype: "sacrifice",
    reward: "Gain +1 End Reward Sacrifice.",
    immediate: { sacrifices: 1 },
    synergy: ["ultimateSacrifice", "treasuryBill"],
    baseScore: 86,
  },
  completeChaos: {
    id: "completeChaos",
    name: "Complete Chaos",
    archetype: "greed",
    reward: "After finishing a Challenge, get an additional random Beacon reward.",
    synergy: ["rainbow", "aqua", "orange"],
    baseScore: 86,
  },
};

export const TRIAL_IDS = [
  "hubris",
  "ultimateSacrifice",
  "gamblingBeast",
  "warmthDevourer",
  "treasuryBill",
  "sideHustle",
  "adrenalineJunkie",
  "lightsOut",
  "allIn",
  "dyingLight",
  "monochromokopia",
  "chronotrigger",
];

export const TRIALS = {
  hubris: {
    id: "hubris",
    name: "Hubris",
    tier: "S",
    objective: "Complete 10 challenges.",
    penalty: "Dying within the next 10 challenges ends the lootrun.",
    reward: "+1 End Reward Reroll and +1 Sacrifice.",
    immediate: { rewardRerolls: 1, sacrifices: 1 },
    danger: 92,
    baseScore: 92,
  },
  ultimateSacrifice: {
    id: "ultimateSacrifice",
    name: "Ultimate Sacrifice",
    tier: "S",
    objective: "Complete 10 challenges.",
    penalty: "For the next 10 challenges, all boon effects are disabled.",
    reward: "+2 End Reward Sacrifices.",
    immediate: { sacrifices: 2 },
    danger: 84,
    baseScore: 94,
  },
  gamblingBeast: {
    id: "gamblingBeast",
    name: "Gambling Beast",
    tier: "A",
    objective: "Active immediately; normally taken as the second trial to end a run.",
    penalty: "Lose 300 + 90(n-1) seconds after each completed challenge.",
    reward: "Gain +1 End Reward Reroll after each completed challenge if the timer can pay the penalty.",
    danger: 76,
    baseScore: 86,
  },
  warmthDevourer: {
    id: "warmthDevourer",
    name: "Warmth Devourer",
    tier: "A",
    objective: "Obtain 20 end reward pulls.",
    penalty: "Lose 1 boon and 1 challenge every challenge completed.",
    reward: "+1 End Reward Reroll and +1 Sacrifice.",
    immediate: { rewardRerolls: 1, sacrifices: 1 },
    danger: 68,
    baseScore: 76,
  },
  treasuryBill: {
    id: "treasuryBill",
    name: "Treasury Bill",
    tier: "C",
    objective: "Obtain 20 end reward pulls.",
    penalty: "Lose a pull every 45 seconds; this removes trial progress.",
    reward: "Boosts current pulls by 75%.",
    danger: 48,
    baseScore: 82,
  },
  sideHustle: {
    id: "sideHustle",
    name: "Side Hustle",
    tier: "A",
    objective: "Open 30 chests.",
    penalty: "Timer is limited to 75 seconds while active.",
    reward: "+2 End Reward Rerolls.",
    immediate: { rewardRerolls: 2 },
    danger: 64,
    baseScore: 74,
  },
  adrenalineJunkie: {
    id: "adrenalineJunkie",
    name: "Adrenaline Junkie",
    tier: "A",
    objective: "Gain 25 Pulls.",
    penalty: "Lose 1 Boon every 25s during interludes.",
    reward: "+2 End Reward Rerolls.",
    immediate: { rewardRerolls: 2 },
    danger: 70,
    baseScore: 78,
  },
  lightsOut: {
    id: "lightsOut",
    name: "Lights Out",
    tier: "C",
    objective: "Defeat 25 Radiant challenge mobs.",
    penalty: "Receive 2 Radiant chance curses every challenge.",
    reward: "Cleanse all Radiant curses to gain +5 Pulls per curse.",
    danger: 70,
    baseScore: 66,
  },
  allIn: {
    id: "allIn",
    name: "All In",
    tier: "B",
    objective: "Complete 10 challenges.",
    penalty: "For the next 10 challenges, curse effects are doubled.",
    reward: "Convert each sacrifice into 3 End Reward Rerolls.",
    danger: 80,
    baseScore: 62,
  },
  dyingLight: {
    id: "dyingLight",
    name: "Dying Light",
    tier: "A",
    objective: "Obtain Boons totalling 1000% Potency.",
    penalty: "Boons lose 5% potency every 2.5s, one by one.",
    reward: "Rainbow Beacons now grant +1 Sacrifice.",
    danger: 78,
    baseScore: 74,
  },
  monochromokopia: {
    id: "monochromokopia",
    name: "Monochromokopia",
    tier: "C",
    objective: "Gain 30 pulls.",
    penalty: "Completed beacon colors become obscured for 7 challenges.",
    reward: "Add an additional White, Grey, and Dark Grey beacon to your pool.",
    danger: 50,
    baseScore: 58,
  },
  chronotrigger: {
    id: "chronotrigger",
    name: "Chronotrigger",
    tier: "S",
    objective: "Complete 12 challenges.",
    penalty: "For the next 12 challenges, you cannot gain time in any way.",
    reward: "Green Beacons cleanse 15% curses and increase your pulls by 3.5%.",
    danger: 88,
    baseScore: 90,
  },
};

export const DEFAULT_OFFERED_BEACONS = [
  { id: "blue", vibrant: false },
  { id: "purple", vibrant: false },
  { id: "yellow", vibrant: false },
];

export const DEFAULT_OFFERED_MISSIONS = [
  "equilibrium",
  "highRoller",
  "redemption",
];

export const DEFAULT_OFFERED_TRIALS = [
  "hubris",
  "ultimateSacrifice",
];

export const MAX_TIMER_SECONDS = 900;
export const GREEN_TIMER_OVER_CAP_SECONDS = 1200;
export const BASE_START_TIMER_SECONDS = 300;
export const BASE_CHALLENGE_CAP = 12;
export const HARD_CHALLENGE_CAP = 100;
export const RED_NO_TIME_BONUS_SECONDS = 150;
